version: '1.0'

networks:
  jenkins:
    diver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080-8100:8080-8100"

    volumes:
      - /etc/nginx:/etc/nginx
      - /var/log/nginx:/var/log/nginx  # 将日志目录挂载到宿主机
    environment:   # 设置时区  新版 docker-compose  环境变量设置方式： mapping ?
      - TZ=Asia/Shanghai
    networks:
      - jenkins
    restart: always

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      - jenkins
    restart: always

volumes:
  jenkins_home:
